name: Change Tracking
  
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      Revisionversion:
         description: 'CURL Revision version'
         required: true
         default: '2'
  release:
    types: [published]


jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: run curl
        id: testcases
        run: |

            version=$((${{github.event.inputs.Revisionversion}}+1))
            echo "newversion=$((version))"
            echo "CURLVERSION=$((version))" >> $GITHUB_OUTPUT
            
            curl -X 'POST' \
              'https://api.newrelic.com/graphql' \
              -H 'Content-Type: application/json' \
              -H 'API-Key: NRAK-VOIHYB7MPC7PBTIBPW9M9G657SE' \
              --data-binary '{{"query":"mutation {\n  changeTrackingCreateDeployment(deployment: {version: \"'"$version"'\", user: \"t.dineshbabu@cloudeq.com\", groupId: \"78641\", entityGuid: \"MzY3OTk4NXxBUE18QVBQTElDQVRJT058MTMwMjU5NzI5NQ\", description: \"create a new marker\", deploymentType: BASIC, deepLink: \"https://github.com/DINESHBABU1998/nrtrack\", commit: \"INSERT_A_COMMIT_HASH\", changelog: \"test log\"}) {\n    changelog\n    commit\n    deepLink\n    deploymentId\n    deploymentType\n    description\n    entityGuid\n    groupId\n    user\n    version\n  }\n}\n", "variables":""}'
      
      # - run : echo 'FAILURES:{{ steps.testcases.output.CURLVERSION }}'
      #   if : failure()




